server:
    port: 8002

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456

website:
    domain-name: news.com

freemarker:
  html:
    article: /usr/local/tomcat0/webapps/news-frontend/portal