##################
# Admin service
#################

server:
    tomcat:
        uri-encoding: UTF-8
        max-swallow-size: -1

######################
# project config
######################
spring:
    profiles:
        active: dev
    application:
        name: service-admin
    jackson:
        date-format: yyy-MM-dd HH:mm:ss
        time-zone: GMT-8
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: password
        hikari:
            connection-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 20
            auto-commit: true
            idle-timeout: 600000
            pool-name: DateSourceHikariCP
            max-lifetime: 1800000
            connection-test-query: SELECT 1
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017
            database: news
mybatis:
    type-aliases-package: com.panda.pojo
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers: com.panda.my.mapper.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true
        
