##################
# Article service
#################

server:
    tomcat:
        uri-encoding: UTF-8
        max-swallow-size: -1

######################
# project config
######################
spring:
    profiles:
        active: dev
    application:
        name: service-article
    jackson:
        date-format: yyy-MM-dd HH:mm:ss
        time-zone: GMT-8
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: password
        hikari:
            connection-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 20
            auto-commit: true
            idle-timeout: 600000
            pool-name: DateSourceHikariCP
            max-lifetime: 1800000
            connection-test-query: SELECT 1
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017
            database: news
    freemarker:
        charset: UTF-8
        content-type: text/html
        suffix: .ftl
        template-loader-path: classpath:/templates/
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: admin
        password: admin
        virtual-host: news-dev
mybatis:
    type-aliases-package: com.panda.pojo
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers: com.panda.my.mapper.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server-7000:7000/eureka/,http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/,
ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2

logging:
    level:
        com.panda.api.controller.user.UserControllerApi: debug
feign:
    client:
        config:
            service-user:
                loggerLevel: FULL
