##################
# User service
#################

server:
    tomcat:
        uri-encoding: UTF-8
        max-swallow-size: -1

######################
# project config
######################
spring:
    profiles:
        active: dev
    application:
        name: service-user
    jackson:
        date-format: yyy-MM-dd HH:mm:ss
        time-zone: GMT-8
