##################
# zuul service
#################

server:
    port: ${port:7070}
    tomcat:
        uri-encoding: UTF-8

######################
# project config
######################
spring:
    application:
        name: springcloud-zuul
zuul:
    prefix: /api
    routes:
        service-article:
            path: /service-article/**
            url: http://127.0.0.1:8007
            ## example path
            ## http://localhost:7070/api/service-article/api/service-article/article/portal/get?articleId=210721G32YXRSY80
