##################
# zuul service
#################

server:
    port: ${port:7070}
    tomcat:
        uri-encoding: UTF-8

######################
# project config
######################
spring:
    application:
        name: springcloud-zuul
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: 123456
zuul:
    prefix: /api
    routes:
        service-article:
            path: /service-article/**
            service-id: service-article
            ##url: http://127.0.0.1:8007
            ## example path
            ## http://localhost:7070/api/service-article/api/service-article/article/portal/get?articleId=210721G32YXRSY80
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server-7000:7000/eureka/,http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/
ipBlacklist:
    maxRequestCount: ${threshold:10}
    interval: ${interval:10}
    frozenDuration: ${frozenDuration:15}