##################
# zuul service
#################

server:
    port: ${port:7070}
    tomcat:
        uri-encoding: UTF-8

######################
# project config
######################
spring:
    application:
        name: springcloud-zuul
zuul:
    routes:
        service-article:
            path: /service-article/**
            url: http://127.0.0.1:8007
    prefix: /api