##################
# config service
#################

server:
    port: ${port:7080}
    tomcat:
        uri-encoding: UTF-8

######################
# project config
######################
spring:
    application:
        name: springcloud-config

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server-7000:7000/eureka/,http://eureka-server-7001:7001/eureka/,http://eureka-server-7002:7002/eureka/
