##################
# File service
#################

server:
    tomcat:
        uri-encoding: UTF-8
        max-swallow-size: -1

######################
# project config
######################
spring:
    profiles:
        active: dev
    application:
        name: service-fs
    jackson:
        date-format: yyy-MM-dd HH:mm:ss
        time-zone: GMT-8
    servlet:
        multipart:
            max-file-size: 512000
            max-request-size: 512000
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017
            database: news

######################
# fastdfs config
######################
fdfs:
    connection-time: 30
    so-timeout: 30
    tracker-list: 127.0.0.1:22122