server:
  port: 8014
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: service-search
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true