##################
# eureka service
#################

server:
    tomcat:
        uri-encoding: UTF-8
        max-swallow-size: -1

######################
# project config
######################
spring:
    profiles:
        active: dev
    application:
        name: springcloud-eureka
eureka:
    instance:
        hostname: localhost
    client:
        # disable self-registry
        register-with-eureka: false
        # disable self-fetch
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/