##################
# eureka service
#################

server:
    tomcat:
        uri-encoding: UTF-8
        max-swallow-size: -1

######################
# project config
######################
spring:
    profiles:
        active: dev
    application:
        name: springcloud-eureka