##################
# eureka service
#################

server:
    port: ${port:7000}
    tomcat:
        uri-encoding: UTF-8
        max-swallow-size: -1

######################
# project config
######################
spring:
    profiles:
        active: dev
    application:
        name: springcloud-eureka-cluster
eureka:
    instance:
        hostname: eureka-server-${server.port}
    replica-server-port1: ${p1:7001}
    replica-server-port2: ${p2:7002}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server-${eureka.replica-server-port1}:7001/eureka/,http://eureka-server-${eureka.replica-server-port2}:7002/eureka/